language: python
python:
  - "2.7"

install:
  "pip install -r requerimientos.txt"

before script:
  - autopep8 -ir *
  - flake8 --max-complexity=8 --exclude=*.txt, *.md, *.pyc *

script:
  - python TestCalculadora.py
  - coverage run --branch TestCalculadora.py
  - cd tests
  - lettuce